# Regresión lineal en Python
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [2]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [4]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [5]:
X = data[feature_cols]
Y = data["Sales"]

In [7]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1)
selector = selector.fit(X,Y)

/home/alex/anaconda3/envs/Curso-ML-Python/lib/python3.7/site-packages/sklearn/utils/validation.py:72: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  "will result in an error", FutureWarning)


In [8]:
selector.support_

array([ True,  True, False])

In [9]:
selector.ranking_

array([1, 1, 2])

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
X_pred = X[["TV", "Radio"]]

In [13]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [14]:
lm.intercept_

2.921099912405138

In [15]:
lm.coef_

array([0.04575482, 0.18799423])

In [17]:
lm.score(X_pred, Y)

0.8971942610828957