# El método de k-means

In [1]:
import numpy as np

In [2]:
data = np.random.random(90).reshape(30,3)
data

array([[0.22516078, 0.66480483, 0.49221683],
       [0.91040259, 0.94510419, 0.56748544],
       [0.15999013, 0.26712181, 0.82229747],
       [0.26005132, 0.69532247, 0.69557649],
       [0.42122834, 0.15609435, 0.00933888],
       [0.40660126, 0.38420493, 0.07067044],
       [0.57337914, 0.59743187, 0.71172781],
       [0.32577196, 0.60062288, 0.97736884],
       [0.1871061 , 0.73562278, 0.53923661],
       [0.97830161, 0.77843636, 0.00167274],
       [0.06706709, 0.42306204, 0.87880944],
       [0.69425511, 0.62021979, 0.38137269],
       [0.9582661 , 0.42671209, 0.16685148],
       [0.4283708 , 0.89558229, 0.72689472],
       [0.79271465, 0.28933807, 0.97260675],
       [0.07142181, 0.58781216, 0.54035853],
       [0.45859394, 0.94122558, 0.50811761],
       [0.60558641, 0.38513419, 0.33632697],
       [0.11093922, 0.76293694, 0.80281425],
       [0.1212839 , 0.24363766, 0.60864749],
       [0.87981075, 0.49606295, 0.3721274 ],
       [0.29102388, 0.44548942, 0.61640555],
       [0.

In [3]:
c1 = np.random.choice(range(len(data)))
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]])
clust_centers

array([[0.79271465, 0.28933807, 0.97260675],
       [0.27120068, 0.82268049, 0.8077451 ]])

In [4]:
from scipy.cluster.vq import vq

In [5]:
vq(data, clust_centers)

(array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 1, 1, 1, 0], dtype=int32),
 array([0.35581243, 0.69375164, 0.56676716, 0.17007695, 1.04098077,
        0.86825871, 0.38893198, 0.28471006, 0.29452971, 1.07317376,
        0.4543298 , 0.63384448, 0.83397869, 0.19119075, 0.        ,
        0.40813025, 0.37275435, 0.67010882, 0.17110623, 0.63040106,
        0.64101197, 0.42341101, 0.38784427, 0.2579655 , 0.13915006,
        0.57344661, 0.1345441 , 0.79175862, 0.        , 0.56508635]))

In [6]:
from scipy.cluster.vq import kmeans

In [7]:
kmeans(data, clust_centers)

(array([[0.70903875, 0.44087999, 0.46548668],
        [0.21896215, 0.62933739, 0.66754533]]),
 0.352940003641972)

In [8]:
kmeans(data, 2)

(array([[0.21896215, 0.62933739, 0.66754533],
        [0.70903875, 0.44087999, 0.46548668]]),
 0.352940003641972)